### ISSUE TITLE
Can't run on Android 4.2.0

### ISSUE THREAD

**Issue by luizfx22** [Lucas-Gardini/NocoDB-Desktop#1]
Hello, I'm trying to run this app on android 4.2.0 but it won't open. What to do?

**Comment by Lucas-Gardini** [comment]
> Hello, I'm trying to run this app on android 4.2.0 but it won't open. What to do?

Are you extremelly dumb? Can't you read desktop?

**Comment by luizfx22** [comment]
But my desktop is a 2012 samsung tablet, I can't affort to have a windows computer 😢

**Comment by Lucas-Gardini** [comment]
🤬
